{% set version = "0.7.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fusen
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fusen_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fusen/fusen_{{ version }}.tar.gz
  sha256: 14cafd634dbc6cd31b096c82e197e9263c3c0c0ee4ea19205af9c8722f185b5a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-attachment
    - r-cli
    - r-desc
    - r-devtools
    - r-glue
    - r-here >=1.0.0
    - r-lightparser
    - r-magrittr
    - r-roxygen2
    - r-stringi
    - r-tibble
    - r-tidyr
    - r-usethis >=2.0.0
    - r-yaml
  run:
    - r-base
    - r-attachment
    - r-cli
    - r-desc
    - r-devtools
    - r-glue
    - r-here >=1.0.0
    - r-lightparser
    - r-magrittr
    - r-roxygen2
    - r-stringi
    - r-tibble
    - r-tidyr
    - r-usethis >=2.0.0
    - r-yaml

test:
  commands:
    - $R -e "library('fusen')"           # [not win]
    - "\"%R%\" -e \"library('fusen')\""  # [win]

about:
  home: https://thinkr-open.github.io/fusen/
  dev_url: https://github.com/Thinkr-open/fusen
  license: MIT
  summary: Use Rmarkdown First method to build your package. Start your package with documentation, functions, examples and tests in the same unique file. Everything can be set from the Rmarkdown template file provided in your project, then inflated as a package. Inflating the template copies the relevant chunks and sections
    in the appropriate files required for package development.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: fusen
# Title: Build a Package from Rmarkdown Files
# Version: 0.6.0
# Authors@R: c( person("Sebastien", "Rochette", , "sebastienrochettefr@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1565-9313")), person("ThinkR", role = "cph") )
# Description: Use Rmarkdown First method to build your package. Start your package with documentation, functions, examples and tests in the same unique file. Everything can be set from the Rmarkdown template file provided in your project, then inflated as a package. Inflating the template copies the relevant chunks and sections in the appropriate files required for package development.
# License: MIT + file LICENSE
# URL: https://thinkr-open.github.io/fusen/, https://github.com/Thinkr-open/fusen
# Depends: R (>= 3.5.0)
# Imports: attachment, cli, desc, devtools, glue, here (>= 1.0.0), lightparser, magrittr, methods, roxygen2, stats, stringi, tibble, tidyr, tools, usethis (>= 2.0.0), utils, yaml
# Suggests: gert, knitr, pkgload, rcmdcheck, rmarkdown, rstudioapi, styler, testthat (>= 3.2.0), withr
# VignetteBuilder: knitr
# Config/fusen/version: 0.6.0
# Config/testthat/edition: 3
# Config/testthat/parallel: false
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-05-13 13:15:13 UTC; srochett
# Author: Sebastien Rochette [aut, cre] (<https://orcid.org/0000-0002-1565-9313>), ThinkR [cph]
# Maintainer: Sebastien Rochette <sebastienrochettefr@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-05-14 07:33:19 UTC
